/*
CHAT (ЧАТЫ)
- cid (ID чата)
- first_uid (ID владельца чата, в диалоге - тот, кто первым написал)
- second_uid (ID 2 участника диалога, в группах = 0)
- mid (ID последнего сообщения в чате)
- chatname (название чата, в диалоге - пусто)
- created_at (дата создания, в диалоге - дата отправки 1-го сообщения)
*/


DROP TABLE IF EXISTS chat CASCADE;
CREATE TABLE chat(
	cid INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_uid INT NOT NULL REFERENCES users(uid),
	second_uid INT NOT NULL DEFAULT 0,
	mid INT NOT NULL DEFAULT 0,
	chatname VARCHAR(32) NOT NULL DEFAULT '',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/*
CHAT_MEMBER (УЧАСТНИКИ ЧАТОВ)
- cid (ID чата)
- uid (ID пользователя)
- mid (ID последнего прочитанного этим пользователем сообщения)
- joined_at (дата вступления в чат, в диалоге - дата 1-го сообщения)
*/


DROP TABLE IF EXISTS chat_member CASCADE;
CREATE TABLE chat_member(
	cid INT NOT NULL REFERENCES chat(cid),
	uid INT NOT NULL REFERENCES users(uid),
	mid INT NOT NULL DEFAULT 0,
	joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/*
MESSAGE (СООБЩЕНИЯ)
- global_mid (глобальный ID сообщения)
- cid (ID чата)
- mid (локальный ID сообщения)
- sid (ID отправителя сообщения)
- content (текст сообщения)
- send_at (дата отправки)
- updated_at (дата последнего изменения)
- remove_state (статус удалённости сообщения)
*/


DROP TABLE IF EXISTS message CASCADE;
CREATE TABLE message(
	global_mid INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	cid INT NOT NULL REFERENCES chat(cid),
	mid INT NOT NULL,
	sid INT NOT NULL REFERENCES users(uid),
	content VARCHAR(4096) NOT NULL,
	send_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	remove_state BOOLEAN NOT NULL DEFAULT FALSE
);


-- ЗАПОЛНЯЕМ ТЕСТАМИ

/*

INSERT INTO chat(first_uid, second_uid, mid, chatname)
VALUES
(1, 2, 4, ''), -- 1-й чат - диалог 
(2, 0, 3, 'Test Group'), -- 2-й чат - группа
(3, 1, 1, ''); -- 3-й чат



INSERT INTO chat_member(cid, uid)
VALUES
-- диалог Вани и Ромы
(1, 1),
(1, 2),

-- группа: Стеша, Рома, Ваня
(2, 3),
(2, 2),
(2, 1),

-- диалог Стеши и Вани
(3, 3), 
(3, 1);


INSERT INTO message(cid, mid, sid, content)
VALUES
-- сообщения диалога Вани и Ромы
(1, 1, 1, 'Здаров'),
(1, 2, 2, 'Хай бро'),
(1, 3, 1, 'Поможешь с курсачом?'),
(1, 4, 2, 'Конечно бро =)'),

-- сообщения группы: Стеша, Рома, Ваня
(2, 1, 3, 'Message to the chat'),
(2, 2, 2, 'На русском пиши'),
(2, 3, 3, 'Аахаххах'),

-- сообщения диалога Стеши и Вани
(3, 1, 3, 'ЖДУ ДЕНЕГ!!!!');
*/